### ISSUE TITLE
Interest in updates? 

### ISSUE THREAD

**Issue by zacMode** [earlye/dropwizard-multi-config#5]
@earlye Thanks so much for this work! 

We have a need for a variation of the logic you've built and are wondering if you are interested in us contributing this back (would include major, breaking changes) or if we should fork and pursue the changes in parallel? 

A high level change summary:
- Add support for resource files (files included in the jar)
- Remove need for `MultipleConfigurationApplication` and instead use the standard Application (configuration argument will be a string with some sort of delimiter, e.g. `java -jar service.jar server 'base.yaml:override1.yaml:override2.yaml'`)
- MultipleConfigurationProvider will be able to be used as is, or composed with other providers (e.g. with [SubstitutingSourceProvider](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-configuration/src/main/java/io/dropwizard/configuration/SubstitutingSourceProvider.java)

I realize this repo is quite old at this point, so you very likely have moved on to other things. Just wanted to reach out and see what works best for you.

Thanks!

**Comment by earlye** [comment]
I have definitely moved on to other things 😆 

I honestly don't even remember how this repo works at this point. I'd say go ahead and shoot me a PR, and if I don't respond fast enough for your tastes then proceed in your fork.

**Comment by zacMode** [comment]
> I have definitely moved on to other things 😆

😆  very fair! 

I'll keep you posted, we'll probably develop this internally but i'll eventually make a pr out of it if it seems reasonable!
